---
kind: pipeline
type: docker
name: web

steps:
  - name: install
    image: node:alpine
    commands:
      - npm i --registry=https://registry.npm.taobao.org

  - name: test
    image: node:alpine
    commands:
      - npm run test

  - name: build
    image: node:alpine
    commands:
      - npm run build
      - ls -al
    # script:
      # - echo $USER
      # - cd ~/.ssh
      # - ls -al
      # - rm -rf /root/docs
      # - mkdir /root/docs
      # - cp -r .vuepress/dist/* /root/docs

  # 同一台机器
  # - name: deploy
  #   image: appleboy/drone-scp
  #   settings:
  #     host:
  #       - 111.229.81.101
  #     username: root
  #     password: !1qaz@2WSX
  #     password:
  #       from_secret: ssh_key
  #     port: 22
  #     source:
  #       - .vuepress/dist/*
  #     target: /root/docs
  #     rm: true
      # secrets: [ deploy_key ]
      # key_path: /root/.ssh/ssh_key
      # secrets:
      #   - source: deploy_key
      #     target: ssh_key

  - name: rsync production
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
    settings:
      user: root
      hosts:
        - 111.229.81.101
      source: .vuepress/dist/*
      target: /root/docs
      secrets: [ rsync_key ]

  - name: notify
    image: curlimages/curl
    commands:
      - |
        curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=dbb3fa53-29f8-4394-bfa1-ecce009e8cbb' -H 'Content-Type: application/json' -d '{"msgtype": "text", "text": {"content": "ok"}}'
    when:
      status:
        - failure
        - success