---
kind: pipeline
type: docker
name: web

steps:
  - name: install
    image: node:alpine
    commands:
      - npm i --registry=https://registry.npm.taobao.org

  - name: test
    image: node:alpine
    commands:
      - npm run test

  - name: build
    image: node:alpine
    commands:
      - npm run build
      - ls -al
      # - echo $USER
      # - rm -rf /root/docs
      # - mkdir /root/docs
      # - cp -r .vuepress/dist/* /root/docs

  # - name: rsync production
  #   image: drillster/drone-rsync
  #   environment:
  #     RSYNC_KEY:
  #       from_secret: rsync_key
  #   settings:
  #     user: root
  #     hosts:
  #       - 111.229.81.101
  #     source: .vuepress/dist/*
  #     target: /root/docs
  #     secrets: [ rsync_key ]

  - name: scp files
  image: appleboy/drone-scp
  settings:
    host:
      - 111.229.81.101
    username: root
    password:
      - from_secret: rsync_key
    port: 22
    target: /root/docs
    source: .vuepress/dist/*
