---
kind: pipeline
type: docker
name: web

steps:
  - name: 安装依赖
    image: node:alpine
    commands:
      - npm i --registry=https://registry.npm.taobao.org

  - name: 测试
    image: node:alpine
    commands:
      - npm run test
